# Generated by Django 5.2.5 on 2025-08-31 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data da Análise')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Análise de Rede',
                'verbose_name_plural': 'Análises de Rede',
            },
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cômodo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Problemas')),
                ('analise_rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comodos', to='dashboard.analiserede')),
            ],
            options={
                'verbose_name': 'Cômodo',
                'verbose_name_plural': 'Cômodos',
            },
        ),
        migrations.CreateModel(
            name='DadosSinais',
            fields=[
                ('comodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.comodo')),
                ('dbm', models.FloatField(verbose_name='Potência (dBm)')),
                ('download', models.FloatField(verbose_name='Velocidade de Download (Mbps)')),
                ('upload', models.FloatField(verbose_name='Velocidade de Upload (Mbps)')),
                ('interferencia', models.FloatField(verbose_name='Interferência (%)')),
            ],
            options={
                'verbose_name': 'Dado de Sinal',
                'verbose_name_plural': 'Dados de Sinais',
            },
        ),
    ]
