# Generated by Django 5.2.6 on 2025-09-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossinais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dadossinais',
            name='comodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais', to='dashboard.comodo'),
        ),
    ]
