# Generated by Django 5.2.5 on 2025-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSinais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('dbm', models.FloatField()),
                ('download', models.FloatField()),
                ('upload', models.FloatField()),
                ('interferencia', models.FloatField()),
            ],
            options={
                'verbose_name': 'Dado de Sinal',
                'verbose_name_plural': 'Dados de Sinais',
            },
        ),
    ]